//SQL Table Definitions
CREATE TABLE SILVER_AND_ABOVE
(CID CHAR(10) NOT NULL,
CREDITLINE INT );

CREATE TABLE CUSTOMER
(CID CHAR(10) NOT NULL,
FNAME VARCHAR(15) NOT NULL,
LNAME VARCHAR(15) NOT NULL,
EMAIL VARCHAR(30),
ADDRESS VARCHAR(30),
PHONE CHAR(10),
STATUS CHAR NOT NULL DEFAULT'R',
);

CREATE TABLE CREDIT_CARD
(CCNUMBER CHAR(16) NOT NULL,
SECNUMBER CHAR(3) NOT NULL,
OWNERNAME VARCHAR(15) NOT NULL,
CCType VARCHAR(10) NOT NULL,
BILLADDRESS VARCHAR(30),
EXPDATE DATE,
STOREDCARDCID CHAR(10)
);

CREATE TABLE SHIPPING_ADDRESS
(CID CHAR(10) NOT NULL,
SANAME VARCHAR(30) NOT NULL,
RECEPIENTNAME VARCHAR(30),
STREET VARCHAR(10),
SNUMBER INT,
CITY VARCHAR(15),
ZIP CHAR(5),
STATE CHAR(2),
COUNTRY VARCHAR(15));

CREATE TABLE TRANSACTION
(BID CHAR(10) NOT NULL,
CCNUMBER CHAR(16) NOT NULL,
CID CHAR(10) NOT NULL,
SANAME VARCHAR(30) NOT NULL,
TDATE DATE,
TTAG CHAR DEFAULT'C');
//TTAG options assume C=confirmed, S=Shipped, E=Enroute, D=Delivered, L=Lost

CREATE TABLE BASKET
(CID CHAR(10) NOT NULL,
BID CHAR(10) NOT NULL);

CREATE TABLE APPEARS_IN
(BID CHAR(10) NOT NULL,
PID CHAR(10) NOT NULL,
QUANTITY INT,
PRICESOLD DECIMAL(10,2));

CREATE TABLE OFFER_PRODUCT
(PID CHAR(10) NOT NULL,
OFFERPRICE DECIMAL(10,2));

CREATE TABLE PRODUCT
(PID CHAR(10) NOT NULL,
PType CHAR, //C=Computer P=Printer L=Laptop M=Miscelenous
PNAME VARCHAR(15),
PPRICE DECIMAL(10,2),
DESCRIPTION VARCHAR(15),
PQUANTITY INT);

CREATE TABLE COMPUTER
(PID CHAR(10) NOT NULL,
CPUTYPE VARCHAR(10));

CREATE TABLE PRINTER
(PID CHAR(10) NOT NULL,
PRINTER TYPE VARCHAR(10),
RESOLUTION VARCHAR(10));

CREATE TABLE LAPTOP
(PID CHAR(10) NOT NULL,
BTYPE VARCHAR(15),
WEIGHT INT);